# Generated by Django 5.0.2 on 2024-03-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=10)),
                ('repeatpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
