# Generated by Django 5.0.2 on 2024-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_user_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
