# Generated by Django 5.0.2 on 2024-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_rename_user_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=10)),
                ('repeatpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
