# Generated by Django 5.0.2 on 2024-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_user2_delete_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
            ],
        ),
    ]
