# Generated by Django 5.0.2 on 2024-03-10 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0006_alter_feedback_age_alter_feedback_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='age',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phonenumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^[0-9]{10}$')]),
        ),
    ]
