# Generated by Django 5.0.2 on 2024-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0010_rename_message_feedback_textarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='signup1',
            old_name='name',
            new_name='username',
        ),
    ]
