# Generated by Django 5.0.2 on 2024-04-26 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0011_cart_rename_name_signup1_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup1',
            name='email',
        ),
        migrations.AddField(
            model_name='signup1',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup1',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
