# Generated by Django 5.0.2 on 2024-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0012_remove_signup1_email_signup1_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(max_length=100)),
                ('nameoncard', models.CharField(max_length=100)),
                ('creditcardnumber', models.IntegerField(max_length=100)),
                ('expmonth', models.IntegerField(max_length=100)),
                ('expyear', models.IntegerField(max_length=100)),
                ('CVV', models.IntegerField(max_length=100)),
            ],
        ),
    ]
