# Generated by Django 5.0.2 on 2024-04-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0013_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='expmonth',
            field=models.CharField(max_length=100),
        ),
    ]
